name = "minigameplanet-api"
main = "src/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "PLAYERS"
id = "9331e298c0514faa851dc40f1d072de6"

[[d1_databases]]
binding = "DB"
database_name = "minigameplanet"
database_id = "49e12166-cc1b-40a1-ad7c-e87424157c3d"

[durable_objects]
bindings = [
  { name = "GAME_ROOM", class_name = "GameRoom" },
  { name = "GAME_LOBBY", class_name = "GameLobby" }
]

[[migrations]]
tag = "v1"
new_classes = ["GameRoom", "GameLobby"]
